### ISSUE TITLE
FIRST-S00065 seems to duplicate FIRST-S00029

### ISSUE THREAD

**Issue by petergs** [SumoLogic/cloud-siem-content-catalog#33]
FIRST-S00065 (called First Seen Successful Authentication From Unexpected Country (SILENT MODE)) seems to be exactly the same as FIRST-S00029 (called First Seen Successful Authentication From Unexpected Country). FIRST-S00065 arrived as [part of the November 7th 2024 Content Release](https://help.sumologic.com/release-notes-cse/2024/11/07/content/#:~:text=%5BNew%5D-,FIRST%2DS00065,-First%20Seen%20Successful).

Could you clarify the intended purpose of this rule or confirm it's a duplicate?

**Comment by jc-sumo** [comment]
@petergs Thanks for pointing this out. This is indeed a duplicate. The original (FIRST-S00029) is disabled by default (you have to turn it on if you want to use it). It was disabled because we didn't have a high degree of certainty it wouldn't generate excessive noise, in subsequent testing we determined it was acceptable to have it enabled, so we released an enabled version (FIRST-S00065). However, it was missed that we had to clean up the original iteration. We've issued guidance as part of this weeks content release that it will be deleted in ~2 weeks and to migrate any tuning expressions associated with the original to the newer iteration that is not disabled by default.
